<a href="https://colab.research.google.com/github/tharushidambarage/BioLens-AI-Facial-Analyzer/blob/notebooks/01_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

print(torch.__version__)
print("GPU:", torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

2.11.0+cu128
GPU: True
Tesla T4

In [2]:
import json
import os

kaggle_credentials = {
    "username": "tharushidambarage",
    "key": "KGAT_eeb56e1cf8b59c3a0456f6208fbb2e6d"
}

os.makedirs("/root/.kaggle", exist_ok=True)

with open("/root/.kaggle/kaggle.json", "w") as f:
    json.dump(kaggle_credentials, f)

os.chmod("/root/.kaggle/kaggle.json", 0o600)

print("Kaggle API configured successfully!")

Kaggle API configured successfully!

In [3]:
!kaggle datasets list -s celeba

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                   title                                               size  lastUpdated                 downloadCount  voteCount  usabilityRating
----------------------------------------------------  -------------------------------------------  -----------  --------------------------  -------------  ---------  ---------------
jessicali9530/celeba-dataset                          CelebFaces Attributes (CelebA) Dataset        1427750792  2018-06-01 20:08:48.043000         242288       1871  0.7647059
kushsheth/face-vae                                    CelebA Dataset                                1427750792  2024-04-25 16:50:56.483000           2928         20  0.88235295
badasstechie/celebahq-resized-256x256                 CelebA-HQ resized (256x256)                    296807591  2021-04-30 14:24:53.643000          19810         88  0.75
quadeer15sh/celeba-face-recognition-triplets          CelebA Face Recognition Triplets               242120999  2023-09-24 13:41:22.197000           2166         59  0.8235294
zuozhaorui/celeba                                     celeba                                        2835856818  2018-11-03 05:29:21.367000           1962         27  0.375
ashishjangra27/gender-recognition-200k-images-celeba  Gender Classification 200K Images | CelebA    1415953309  2020-05-22 20:15:23.137000           7936         68  0.8125
lamsimon/celebahq                                     celeba-hq                                     2739646496  2020-07-28 14:46:35.690000           8435         47  0.375
attentionlayer241/celeba-spoof-for-face-antispoofing  CelebA Spoof For Face AntiSpoofing           77246082883  2021-05-31 15:05:19.187000          22735         43  0.375
ipythonx/celebamaskhq                                 CelebAMask-HQ                                 3151646544  2022-07-22 11:50:18.620000           3632         21  0.5625
mabdullahsajid/celeba-spoofing                        CelebA Spoofing Dataset                      77214634060  2024-06-08 11:14:09.540000           7641          5  0.6875
therealcyberlord/50k-celeba-dataset-64x64             50k Celeba Dataset 64x64                        81918629  2023-03-05 19:38:03.733000           1988          7  0.625
kimjiyeop/celeba-128-onlybg                           CelebA-128-OnlyBG                              370042405  2022-06-13 12:51:54.817000            517         11  0.6875
trainingdatapro/celeba-spoof-dataset                  CelebA Spoof Dataset - Real People             345141693  2024-02-06 15:48:01.877000            681         10  1
farzadnekouei/50k-celebrity-faces-image-dataset       50K Celebrity Faces Image Dataset              349562845  2023-08-03 19:26:10.547000           2775         93  0.625
ahmedshawaf/celeba                                    celeba                                        1414484275  2020-04-07 21:56:35                   261          4  0.3125
denislukovnikov/celebahq256-images-only               CelebA-HQ-256 (images only)                   3022447909  2022-10-07 16:59:33.433000           1079          7  0.5625
kiernanmcguigan/celebadataset384x384                  CelebA-Dataset-384x384                        6767879827  2022-04-04 20:09:22.883000             73          9  0.6875
dmitriypushkarev/cineface10                           CineFace1.0 Actors Faces Dataset Not Celeba   2090020408  2022-04-24 23:51:06.727000            152          7  0.7058824
wannad1e/celeba-500-label-folders                     CelebA-Face | 500 Identities Dataset           253708284  2024-02-05 13:21:23.767000            437          5  0.75
nikhilbartwal001/celeba                               Celeb Faces Attributes Dataset (CelebA)       1414484275  2021-02-23 13:27:41.947000            627          8  0.75

In [6]:
# Move to Colab working directory
%cd /content

# Download CelebA dataset from Kaggle
!kaggle datasets download -d jessicali9530/celeba-dataset

/content
Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/jessicali9530/celeba-dataset
License(s): other
celeba-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)

In [7]:
import os

print("ZIP exists:", os.path.exists("/content/celeba-dataset.zip"))
print("ZIP size (GB):", round(os.path.getsize("/content/celeba-dataset.zip")/1024**3,2))

ZIP exists: True
ZIP size (GB): 1.33

In [11]:
import os

extract_path = "/content/celeba/img_align_celeba"

if os.path.exists(extract_path):
    print("Images extracted so far:", len(os.listdir(extract_path)))
else:
    print("Extraction folder not created yet.")

Images extracted so far: 1

In [12]:
import shutil
import os

if os.path.exists("/content/celeba"):
    shutil.rmtree("/content/celeba")

print("Partial extraction removed.")

Partial extraction removed.

In [14]:
!unzip -j /content/celeba-dataset.zip "list_attr_celeba.csv" -d /content/celeba_metadata

Archive:  /content/celeba-dataset.zip
  inflating: /content/celeba_metadata/list_attr_celeba.csv

In [15]:
import pandas as pd

attr = pd.read_csv("/content/celeba_metadata/list_attr_celeba.csv")
attr.head()

,image_id,5_o_Clock_Shadow,Arched_Eyebrows,Attractive,Bags_Under_Eyes,Bald,Bangs,Big_Lips,Big_Nose,Black_Hair,...,Sideburns,Smiling,Straight_Hair,Wavy_Hair,Wearing_Earrings,Wearing_Hat,Wearing_Lipstick,Wearing_Necklace,Wearing_Necktie,Young
0,000001.jpg,-1,1,1,-1,-1,-1,-1,-1,-1,...,-1,1,1,-1,1,-1,1,-1,-1,1
1,000002.jpg,-1,-1,-1,1,-1,-1,-1,1,-1,...,-1,1,-1,-1,-1,-1,-1,-1,-1,1
2,000003.jpg,-1,-1,-1,-1,-1,-1,1,-1,-1,...,-1,-1,-1,1,-1,-1,-1,-1,-1,1
3,000004.jpg,-1,-1,1,-1,-1,-1,-1,-1,-1,...,-1,-1,1,-1,1,-1,1,1,-1,1
4,000005.jpg,-1,1,1,-1,-1,-1,1,-1,-1,...,-1,-1,-1,-1,-1,-1,1,-1,-1,1

In [16]:
import pandas as pd

attr = pd.read_csv("/content/celeba_metadata/list_attr_celeba.csv")

# Keep only the attributes we need
subset = attr[[
    "image_id",
    "Black_Hair",
    "Brown_Hair",
    "Blond_Hair",
    "Eyeglasses"
]].copy()

# Convert -1 to 0
for col in subset.columns[1:]:
    subset[col] = subset[col].replace(-1, 0)

# Keep images with one of the three hair colours
subset = subset[
    (subset["Black_Hair"] == 1) |
    (subset["Brown_Hair"] == 1) |
    (subset["Blond_Hair"] == 1)
]

# Random sample
subset = subset.sample(n=5000, random_state=42)

print("Selected images:", len(subset))
subset.head()

Selected images: 5000

          image_id  Black_Hair  Brown_Hair  Blond_Hair  Eyeglasses
1648    001649.jpg           1           0           0           0
58808   058809.jpg           0           1           0           0
76033   076034.jpg           0           1           0           0
112060  112061.jpg           0           1           0           0
39206   039207.jpg           1           0           0           0

In [17]:
subset.to_csv("/content/celeba_metadata/biolens_subset.csv", index=False)

In [18]:
# Extracting only 5000 images

In [19]:
import zipfile
import os
from tqdm import tqdm

zip_path = "/content/celeba-dataset.zip"
output_dir = "/content/BioLensSubset"

os.makedirs(output_dir, exist_ok=True)

# Read selected filenames
filenames = set(subset["image_id"])

with zipfile.ZipFile(zip_path, "r") as z:
    members = [m for m in z.namelist() if m.split("/")[-1] in filenames]

    for member in tqdm(members):
        z.extract(member, output_dir)

print("Extraction complete.")

100%|██████████| 5000/5000 [00:00<00:00, 7141.07it/s]

Extraction complete.

In [20]:
import glob

images = glob.glob("/content/BioLensSubset/**/*.jpg", recursive=True)

print("Images extracted:", len(images))
print(images[:5])

Images extracted: 5000
['/content/BioLensSubset/img_align_celeba/img_align_celeba/136145.jpg', '/content/BioLensSubset/img_align_celeba/img_align_celeba/080495.jpg', '/content/BioLensSubset/img_align_celeba/img_align_celeba/071991.jpg', '/content/BioLensSubset/img_align_celeba/img_align_celeba/000507.jpg', '/content/BioLensSubset/img_align_celeba/img_align_celeba/140268.jpg']

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [23]:
import os

print(os.path.exists("/content/drive/MyDrive"))
print(os.listdir("/content/drive"))

True
['MyDrive', '.shortcut-targets-by-id', '.Trash-0', '.Encrypted']

In [24]:
import os

base = "/content/drive/MyDrive/BioLens"

folders = [
    base,
    f"{base}/datasets",
    f"{base}/models",
    f"{base}/outputs",
    f"{base}/notebooks"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("✅ Folder structure created.")

✅ Folder structure created.

In [25]:
os.listdir("/content/drive/MyDrive/BioLens")

['datasets', 'models', 'outputs', 'notebooks']

In [26]:
!cp -r /content/BioLensSubset /content/drive/MyDrive/BioLens/datasets/
!cp /content/celeba_metadata/biolens_subset.csv /content/drive/MyDrive/BioLens/datasets/